pull_request_rules:
  - name: CI passes and is dev-dependency package from dependabot
    conditions:
      - check-success=Test
      - check-success=Extension test
      - check-success=Build
      - check-success=Prettier
      - check-success=Eslint
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=^build\(deps-dev\).*$
      - base=main
    actions:
      merge:
        method: merge
